export { PageNotFound } from "./PageNotFound";
export { HomePage } from "./home/HomePage";
export { DashBoardPage } from "./Dashbaord/DashBoardPage";
export { ProductsList } from "./Product/ProductList";
export { ProductDetail } from "./ProdyctDetails";
export { CartPage } from "./cart/cartPage";
export { OrderPage } from "./orders/orderPage";
export { Login } from "./Login";
export { Register } from "./Register";
